# Production environment configuration
stage: prod

# RDS configuration will be handled by Parameter Store from infrastructure stack
# No need to define RDS connection details here anymore

api:
  throttling:
    burstLimit: 5000
    rateLimit: 2000
  caching:
    enabled: true
    ttlInSeconds: 300

monitoring:
  alarms:
    enabled: true
    errorThreshold: 5
    durationThreshold: 5000

logging:
  level: INFO
  retentionDays: 30
  sampling: 0.1

security:
  encryption:
    kmsKeyId: alias/aws/dynamodb
  cors:
    allowOrigin: "https://medical-appointments.example.com"
    allowHeaders: "Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token"
    allowMethods: "GET,POST,OPTIONS"

performance:
  dynamodb:
    billingMode: PAY_PER_REQUEST
  lambda:
    memorySize: 1024
    timeout: 30
    reservedConcurrency: 100
