Resources:
  # RDS Security Group - Temporarily disabled due to VPC configuration issues
  # RDSSecurityGroup:
  #   Type: AWS::EC2::SecurityGroup
  #   Properties:
  #     GroupDescription: Security group for Medical Appointment RDS instance
  #     SecurityGroupIngress:
  #       - IpProtocol: tcp
  #         FromPort: 3306
  #         ToPort: 3306
  #         CidrIp: 0.0.0.0/0
  #         Description: Allow MySQL access (development only)
  #     Tags:
  #       - Key: Name
  #         Value: medical-appointment-rds-sg-${self:provider.stage}
  #       - Key: Service
  #         Value: medical-appointment-scheduling
  #       - Key: Stage
  #         Value: ${self:provider.stage}

  # RDS Master Password Secret
  RDSMasterSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: medical-appointment-rds-${self:provider.stage}
      Description: Master password for Medical Appointment RDS instance
      GenerateSecretString:
        SecretStringTemplate: '{"username": "admin"}'
        GenerateStringKey: password
        PasswordLength: 32
        ExcludeCharacters: '"@/\'
      Tags:
        - Key: Service
          Value: medical-appointment-scheduling
        - Key: Stage
          Value: ${self:provider.stage}

  # RDS Instance - Publicly accessible for development
  RDSInstance:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Delete
    Properties:
      DBInstanceIdentifier: medical-appointments-db-${self:provider.stage}
      DBInstanceClass: db.t3.micro
      Engine: mysql
      EngineVersion: "8.0"
      MasterUsername: admin
      MasterUserPassword: !Sub "{{resolve:secretsmanager:medical-appointment-rds-${self:provider.stage}:SecretString:password}}"
      AllocatedStorage: 20
      MaxAllocatedStorage: 100
      StorageType: gp2
      StorageEncrypted: true
      
      # Network Configuration - Publicly accessible for development  
      PubliclyAccessible: true
      # Use default security group for simplicity
      # VPCSecurityGroups:
      #   - !Ref RDSSecurityGroup
      
      # Backup Configuration
      BackupRetentionPeriod: 1
      DeleteAutomatedBackups: true
      PreferredBackupWindow: "03:00-04:00"
      PreferredMaintenanceWindow: "sun:04:00-sun:05:00"
      
      # Single-AZ for development
      MultiAZ: false
      
      Tags:
        - Key: Name
          Value: medical-appointments-db-${self:provider.stage}
        - Key: Service
          Value: medical-appointment-scheduling
        - Key: Stage
          Value: ${self:provider.stage}
