name: Continuous Integration

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

env:
  AWS_REGION: us-east-1
  NODE_VERSION: '18.x'

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        npm ci
        
    - name: Run unit tests
      run: |
        npm run test:ci
        
    - name: Build TypeScript
      run: |
        npm run build
        
    - name: Validate Serverless configuration
      run: |
        npm install -g serverless@3
        serverless print --stage dev
        
    - name: Validate Infrastructure configuration
      working-directory: infrastructure
      run: |
        npm init -y
        npm install --save-dev serverless-prune-plugin
        serverless print --stage dev
        
    - name: Security audit
      run: |
        npm audit --audit-level moderate
        
    - name: Test summary
      if: always()
      run: |
        echo "✅ CI Pipeline completed successfully!" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "| Check | Status |" >> $GITHUB_STEP_SUMMARY
        echo "|-------|---------|" >> $GITHUB_STEP_SUMMARY
        echo "| Unit Tests | ✅ Passed |" >> $GITHUB_STEP_SUMMARY
        echo "| Build | ✅ Passed |" >> $GITHUB_STEP_SUMMARY
        echo "| Config Validation | ✅ Passed |" >> $GITHUB_STEP_SUMMARY
        echo "| Security Audit | ✅ Passed |" >> $GITHUB_STEP_SUMMARY
